In [19]:
import numpy as np
import pandas as pd

In [20]:
import tensorflow as tf

In [21]:
import tensorflow.keras.utils as tfu

In [22]:
import cv2

In [23]:
import os

In [24]:
foldername = 'All'

In [25]:
list_names = os.listdir(foldername)

In [26]:
datas = []
pathes = []

In [27]:
i=0
for names in list_names:
    imanames = os.listdir(foldername+'/'+names)
    pathes.append(foldername+'/'+names+'/'+imanames[0])
    datas.append(cv2.imread(foldername+'/'+names+'/'+imanames[0]))
    i+=1

In [28]:
from tensorflow.keras.utils import image_dataset_from_directory

In [29]:
pathes

['All/100/100.1.jpg',
 'All/1000/1000.1.jpg',
 'All/10000/10000.1.jpg',
 'All/100000/100000.1.jpg',
 'All/30/30.1.jpg',
 'All/300/300.1.jpg',
 'All/3000/3000.1.jpg']

In [30]:
from tensorflow.keras.utils import load_img

In [31]:
imas = load_img(pathes[2])
resized = tf.image.resize(imas,[900,900])

In [32]:
resized.shape

TensorShape([900, 900, 3])

In [33]:
re_none = (None,resized)

In [34]:
re_none

(None,
 <tf.Tensor: shape=(900, 900, 3), dtype=float32, numpy=
 array([[[ 1.        ,  1.        ,  1.        ],
         [ 1.        ,  1.        ,  1.        ],
         [ 1.        ,  1.        ,  1.        ],
         ...,
         [ 0.6833496 , 19.68335   ,  0.6833496 ],
         [ 0.        , 19.        ,  0.        ],
         [ 0.        , 19.        ,  0.        ]],
 
        [[ 1.        ,  1.        ,  1.        ],
         [ 1.        ,  1.        ,  1.        ],
         [ 1.        ,  1.        ,  1.        ],
         ...,
         [ 0.8020935 , 19.802094  ,  0.8020935 ],
         [ 0.15376282, 19.153763  ,  0.15376282],
         [ 0.        , 19.        ,  0.        ]],
 
        [[ 1.        ,  1.        ,  1.        ],
         [ 1.        ,  1.        ,  1.        ],
         [ 1.        ,  1.        ,  1.        ],
         ...,
         [ 1.        , 20.        ,  1.        ],
         [ 0.41003418, 19.410034  ,  0.41003418],
         [ 0.        , 19.        ,  0.

In [16]:
tfu.img_to_array(imas).shape

(1125, 1146, 3)

In [45]:
import sys
sys.path.insert(0,'..')

In [54]:
from qiaml.autocrop import crop

In [57]:
dattest = crop(pathes[1])

In [60]:
np.shape(dattest)

(835, 835, 3)

In [61]:
resized = tf.image.resize(dattest,[900,900])

In [63]:
np.shape(resized)

TensorShape([900, 900, 3])

<tf.Tensor: shape=(900, 3), dtype=float32, numpy=
array([[ 0.      , 23.      ,  0.      ],
       [ 0.      , 23.      ,  0.      ],
       [ 0.      , 23.819445,  0.      ],
       ...,
       [ 0.      , 11.      ,  0.      ],
       [ 0.      , 11.      ,  0.      ],
       [ 0.      , 11.      ,  0.      ]], dtype=float32)>